### ISSUE TITLE
Multiple calls to ckeditor.js

### ISSUE THREAD

**Issue by GrumpyD** [egeloen/IvoryCKEditorBundle#156]
Hello I have a page with several textareas, each using ckeditor. However I looked into code as I need to have the textareas generated dynamically and I noticed that the ckeditor.js file is linked for each textareas. Is there something I am doing wrong.Or is it standard behaviour that the asset is linked multiple times?

**Comment by adam187** [comment]
@GrumpyD  It's not happening for Me on latest dev version. 
What version of `IvoryCKEditorBundle` and `symfony` are You using ?

**Comment by egeloen** [comment]
Thsi is the current behavior. CKEditor is loaded as much time you have fields. This is done by design in order to work in all cases (especially prototypes collection). Anyway, you can brint the control back as explained [here](https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/usage.md#load-manually-the-library).

**Comment by GrumpyD** [comment]
Thank you.  I had somehow missed that.
