### ISSUE TITLE
input_sync breaking some android and iOs devices

### ISSUE THREAD

**Issue by NeverDesign** [egeloen/IvoryCKEditorBundle#172]
On some Android and iOS devices the input_sync code causes an 'Uncaught TypeError: Cannot read property 'on' of null' javascript error on line 28 of ckeditor_widget.html.php or line 29 of ckeditor_widget.html.twig because the code isn't wrapped in the CKEditor JS check to see if the environment is supported. 

One fix I tested was to change the template to: 

if ( !CKEDITOR.env.mobile ) {
    {{ ckeditor_widget(id, config, inline, input_sync) }}
}

for line 29 of the twig in the vendor bundle. I would implement this by overriding the twig in the app/Resources directory but for some reason it isn't working that way.

**Comment by egeloen** [comment]
Hum, this is something which should be reported to the CKEditor team. The input sync is generated [here](https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Templating/CKEditorHelper.php#L96-L101). So, basically, we use the result of `CKEditor.replace` which is an instance of the CKEditor element according to the [doc](http://docs.ckeditor.com/#!/api/CKEDITOR) and we call `on` which is part of the API (See [here](http://docs.ckeditor.com/#!/api/CKEDITOR.editor)). So, IMO, the `on` function should be comptatible with all devices and if there is something broken, it should be fixed in CKEditor itself.

**Comment by cordoval** [comment]
http://dev.ckeditor.com/wiki/Bugs

**Comment by egeloen** [comment]
@NeverDesign Can you open an issue on the CKEditor bugtracker?

**Comment by egeloen** [comment]
Closing as this issue is not related to this repo
