### ISSUE TITLE
You have requested a non-existent service "templating.helper.assets".   

### ISSUE THREAD

**Issue by JHGitty** [egeloen/IvoryCKEditorBundle#200]
```bash
You have requested a non-existent service "templating.helper.assets".
Ivory\CKEditorBundle\DependencyInjection\Compiler\AssetsHelperCompilerPass->process()
```

composer.json:
```
    "symfony/symfony": "3.0.*",
    "egeloen/ckeditor-bundle": "~4.0@dev",
```

**Comment by JHGitty** [comment]
This issue occurs if you don't have this in your ``config.yml`` file:
```
framework:
  assets: ~
```

I think this should be fixed?

**Comment by egeloen** [comment]
Hum, indeed the bundle always relies on the assets component... It should be optional.

**Comment by egeloen** [comment]
I just read the code and we should update https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Templating/CKEditorHelper.php#L338-L341 to make it optional and update the code which call it to rely on tha fact it is now optional.

**Comment by egeloen** [comment]
So, the plan is the following update https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Templating/CKEditorHelper.php#L338-L341 in order to return the assets component if it exists or null if it does not. Then, just need to move the url resolution part (`getAssetsHelper()->getUrl`) to the `fixPath` method and update the calls accordingly.

Basically, the assets component is here for a two good reasons: 

 * Rewrite the url if your website is not the root directory of your web server
 * Append assets versions to urls.

A PR is really welcome!

**Comment by JHGitty** [comment]
I think it is just the wrong way to check if the assets component exists? I use Symfony Full Stack, upgraded from Symfony 2.8 (where the ``framework.assets`` config did not exist or was not default) - that because I got this issue.

Symfony 2.8 SE:
https://github.com/symfony/symfony-standard/blob/2.8/app/config/config.yml#L33

Symfony 3.0 SE:
https://github.com/symfony/symfony-standard/blob/3.0/app/config/config.yml#L34

**Comment by egeloen** [comment]
I'm a little bit lost here. Your issue is there is not the `asset.packages` (>= 2.8) or the `templating.helper.assets` (< 2.8). In the bundle, we always rely on the `asset.packages` because a BC compiler pass has been added (see [here(https://github.com/egeloen/IvoryCKEditorBundle/blob/master/DependencyInjection/Compiler/AssetsHelperCompilerPass.php)).

Then, if there is a fix which need to be done it is the one about the fact there is no `asset.packages` or `templating.helper.assets` available. Am I right?

**Comment by egeloen** [comment]
Nevermind, I just figure out what is your exact issue. I will provide a PR.

**Comment by egeloen** [comment]
Your issue has been fixed in the referenced PR.
