### ISSUE TITLE
renderDestroy does not call destroy() on JS instance

### ISSUE THREAD

**Issue by nnlugovoy** [egeloen/IvoryCKEditorBundle#265]
in CKEditorRenderer.php there should be a call to destroy() method - otherwise there are issues with admin forms using sonata.formatter.block.formatter when switching between text/markdown/richhtml modes

```diff
    /**         
     * {@inheritdoc}
     */         
    public function renderDestroy($id)
    {

-       return sprintf('if (CKEDITOR.instances["%s"]) { delete CKEDITOR.instances["%s"]; }', $id, $id);
+       return sprintf('if (CKEDITOR.instances["%s"]) { CKEDITOR.instances["%s"].destroy(true); delete CKEDITOR.instances["%s"]; }', $id, $id, $id);
    }
```

**Comment by egeloen** [comment]
Thanks for your feedback about this topic. This is funny because at the very beginning of the bundle, I was using destroy and I needed to switch to delete due to issues but I can't remember right now... 

So basically, you confirm we need to do both (delete + destroy)? I'm not a CKEditor expert at all :)

**Comment by nnlugovoy** [comment]
need both destroy call and delete for proper instance reinitialization.
such case might be only specific for sonata.formatter.block.formatter, and as a workaround for now I use modified widget template with explicit destroy()

**Comment by egeloen** [comment]
Your issue has been fixed by the referenced PR.
