### ISSUE TITLE
CKEditorRenderer - fixConfigContentsCss strips assets version from 'contentsCss'

### ISSUE THREAD

**Issue by praznovskymartin** [egeloen/IvoryCKEditorBundle#283]
In https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Renderer/CKEditorRenderer.php the 'contentsCss' is being fixed by the method 'fixConfigContentsCss', which apply fixPath  on the asset link.
This results a absolute address without the possibility to apply any revisions on this assets, eg.

```
'/bundles/custombundle/css/style.css?rev=1.0' 
```
will be transformed into
```
'https://some.domain.com/bundles/custombundle/css/style.css'
```

Which is kind of issue, if you have strong cacheing in the way.

So the question, demand:
1. Is there any valid reason to fix the contentsCss by this way - remove anything beyond the question mark?
2. Can we add an option to modify this or atleast make the 'fixConfigContentsCss' method public?

**Comment by egeloen** [comment]
@praznovskymartin Thanks for reporting this issue. It sounds like a bug to me since we remove assets version only for (directory path not file path), so, can you try to replace [this line](https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Renderer/CKEditorRenderer.php#L193) with:

``` php
$config['contentsCss'][] = $this->fixUrl($cssContent);
```

If it's working a PR is very welcome :)

**Comment by praznovskymartin** [comment]
Thanks, there you go :)
