### ISSUE TITLE
CKEditor Upload Files/Images

### ISSUE THREAD

**Issue by Luvelnet** [egeloen/IvoryCKEditorBundle#38]
Hi guys,

I try to integrate the filebrowser\* but i can't, is not clear in the documentation. How can i integrate?

Thanks!

**Comment by hero789** [comment]
hi guys , 
i tried the integration but after installation nothing happened , i think i should see upload dialog in ckeditor when insert images right ?
my config :
ivory_ck_editor:
    configs:
        default:
            filebrowserBrowseRoute: 'elfinder'
            filebrowserBrowseRouteParameters: []

**Comment by aristos32** [comment]
My issue is: I want to upload a file in the editor, not use the gallery. So I don't need the 'browse' parameters, right?

I set my upload routing only:
'filebrowserUploadRoute' => 'GeneralGeneralBundle_account_profile_question_photo_upload', 'filebrowserUploadRouteParameters' => array('user_id' => '10', 'responseType' => 'json'),
'filebrowserUploadRouteAbsolute'   => true,

But when I submit I get 'image source url is missing'.

Can you give me a configuration that will work, since I am missing something obvious here.
