### ISSUE TITLE
Multiple forms of same type in the same page

### ISSUE THREAD

**Issue by tagmat** [egeloen/IvoryCKEditorBundle#72]
When you create multiple forms of same type in one page, browser renders CKEditor at the place of first instance of the textarea of first form. because it searches for the id and the id is same for each form (Symfony2 gets data from datatype name).

Instead of calling replace function of ckeditor, it should be a solution to add a class attribute like this:
'attr'=>array('class'=>'ckeditor')

In addition these lines should be removed from ckeditor_widget.html.twig

```
    <script type="text/javascript">
        if (CKEDITOR.instances['{{ id }}']) {
            delete CKEDITOR.instances['{{ id }}'];
        }

        {% for plugin_name, plugin in plugins %}
            CKEDITOR.plugins.addExternal('{{ plugin_name }}', '{{ plugin.path }}', '{{ plugin.filename }}');
        {% endfor %}

        CKEDITOR.replace('{{ id }}', {{ config | raw }});
    </script>
```

**Comment by jstoeffler** [comment]
Just some quick guidance for those facing this issue:

This is indeed a Symfony problem: multiple forms of the same type will have the same ID, which is invalid HTML, and breaks this bundle.

So you need to have different IDs for the CKEDITOR field you use.

There are two approaches I found for this:

**For "older" versions of Symfony** (not sure exactly when it stopped working, I think it's before 2.7)

You can change the form name, this will also change it's id, and all the related fields. More details here http://stackoverflow.com/a/18732386/183904

**For more recent versions of Symfony**

Unfortunately the solution above doesn't work anymore, and I didn't find an elegant solution. What I ended up doing was using a random ID for the field in twig:

    {{ form_row(myForm.body, {'id': random()}) }}

This doesn't seem to break the form logic, the ID isn't used by Symfony. It was not possible to do this in the form type iself, because if you put your id with the 'attr', the field will have 2 ids (...).

Hope this helps !

**Comment by pounard** [comment]
@jstoeffler it does help, thank you so much!

**Comment by egeloen** [comment]
Please can you open a new issue if there is a problem about multiple IDs. IMO, the ID is not used by Symfony but instead the name is used. I can override the generated id in order to make it unique regardless the form type building it and so making the bundle happy when replacing textarea by CKEditor.
